//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具產生。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建 Visual Studio 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Res {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Res() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Res", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 產生Excel報表 的當地語系化字串。
        /// </summary>
        internal static string ButtonMakeExcelReport {
            get {
                return ResourceManager.GetString("ButtonMakeExcelReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增明細 的當地語系化字串。
        /// </summary>
        internal static string Button_Add_Detail {
            get {
                return ResourceManager.GetString("Button_Add_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 取消 的當地語系化字串。
        /// </summary>
        internal static string Button_Cancel {
            get {
                return ResourceManager.GetString("Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 變更密碼 的當地語系化字串。
        /// </summary>
        internal static string Button_Change_Password {
            get {
                return ResourceManager.GetString("Button_Change_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 選擇上傳檔案 的當地語系化字串。
        /// </summary>
        internal static string Button_Choice_Files {
            get {
                return ResourceManager.GetString("Button_Choice_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 選擇上傳圖片 的當地語系化字串。
        /// </summary>
        internal static string Button_Choice_Images {
            get {
                return ResourceManager.GetString("Button_Choice_Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 關閉 的當地語系化字串。
        /// </summary>
        internal static string Button_Close {
            get {
                return ResourceManager.GetString("Button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確認單據 的當地語系化字串。
        /// </summary>
        internal static string Button_Confirm_Doc {
            get {
                return ResourceManager.GetString("Button_Confirm_Doc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 刪除 的當地語系化字串。
        /// </summary>
        internal static string Button_Delete {
            get {
                return ResourceManager.GetString("Button_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 編輯 的當地語系化字串。
        /// </summary>
        internal static string Button_Edit {
            get {
                return ResourceManager.GetString("Button_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增 的當地語系化字串。
        /// </summary>
        internal static string Button_Insert {
            get {
                return ResourceManager.GetString("Button_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增明細 的當地語系化字串。
        /// </summary>
        internal static string Button_Insert_Detail {
            get {
                return ResourceManager.GetString("Button_Insert_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 登出 的當地語系化字串。
        /// </summary>
        internal static string Button_Logout {
            get {
                return ResourceManager.GetString("Button_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 修改 的當地語系化字串。
        /// </summary>
        internal static string Button_Modify {
            get {
                return ResourceManager.GetString("Button_Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 列印 的當地語系化字串。
        /// </summary>
        internal static string Button_Print {
            get {
                return ResourceManager.GetString("Button_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 返回前頁 的當地語系化字串。
        /// </summary>
        internal static string Button_Return {
            get {
                return ResourceManager.GetString("Button_Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 回首頁 的當地語系化字串。
        /// </summary>
        internal static string Button_ReturnIndex {
            get {
                return ResourceManager.GetString("Button_ReturnIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 儲存 的當地語系化字串。
        /// </summary>
        internal static string Button_Save {
            get {
                return ResourceManager.GetString("Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 儲存,並送信 的當地語系化字串。
        /// </summary>
        internal static string Button_SaveAndMail {
            get {
                return ResourceManager.GetString("Button_SaveAndMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 搜尋 的當地語系化字串。
        /// </summary>
        internal static string Button_Search {
            get {
                return ResourceManager.GetString("Button_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 開始上傳檔案 的當地語系化字串。
        /// </summary>
        internal static string Button_Start_FilesUp {
            get {
                return ResourceManager.GetString("Button_Start_FilesUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 開始上傳圖片 的當地語系化字串。
        /// </summary>
        internal static string Button_Start_ImagesUp {
            get {
                return ResourceManager.GetString("Button_Start_ImagesUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確定 的當地語系化字串。
        /// </summary>
        internal static string Button_Sure {
            get {
                return ResourceManager.GetString("Button_Sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確定新增 的當地語系化字串。
        /// </summary>
        internal static string Button_Sure_Insert {
            get {
                return ResourceManager.GetString("Button_Sure_Insert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確定修改 的當地語系化字串。
        /// </summary>
        internal static string Button_Sure_Modify {
            get {
                return ResourceManager.GetString("Button_Sure_Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 直接入庫 的當地語系化字串。
        /// </summary>
        internal static string Button_ToImport {
            get {
                return ResourceManager.GetString("Button_ToImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 更新 的當地語系化字串。
        /// </summary>
        internal static string Button_Update {
            get {
                return ResourceManager.GetString("Button_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 JCIN Information Co. 的當地語系化字串。
        /// </summary>
        internal static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 NT$ 的當地語系化字串。
        /// </summary>
        internal static string CurrencySign {
            get {
                return ResourceManager.GetString("CurrencySign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用中 的當地語系化字串。
        /// </summary>
        internal static string C_product_state_NOR {
            get {
                return ResourceManager.GetString("C_product_state_NOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 停止使用 的當地語系化字串。
        /// </summary>
        internal static string C_product_state_STP {
            get {
                return ResourceManager.GetString("C_product_state_STP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 朝敏國際貿易 的當地語系化字串。
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 1111 的當地語系化字串。
        /// </summary>
        internal static string ePassword {
            get {
                return ResourceManager.GetString("ePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 密碼長度不符(至少6個字元) 的當地語系化字串。
        /// </summary>
        internal static string Err_PasswordLength {
            get {
                return ResourceManager.GetString("Err_PasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 密碼規則不符(需包含英、數位) 的當地語系化字串。
        /// </summary>
        internal static string Err_PasswordRule {
            get {
                return ResourceManager.GetString("Err_PasswordRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 第一頁 的當地語系化字串。
        /// </summary>
        internal static string FirstPage {
            get {
                return ResourceManager.GetString("FirstPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 變更密碼完成，下次登錄請使用新密碼。 的當地語系化字串。
        /// </summary>
        internal static string Info_ChangePassword_Success {
            get {
                return ResourceManager.GetString("Info_ChangePassword_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 關閉視窗 的當地語系化字串。
        /// </summary>
        internal static string Info_Close_Layer {
            get {
                return ResourceManager.GetString("Info_Close_Layer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資料刪除完成 的當地語系化字串。
        /// </summary>
        internal static string Info_Delete_Success {
            get {
                return ResourceManager.GetString("Info_Delete_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 產品圖 的當地語系化字串。
        /// </summary>
        internal static string Info_Detail_Picture {
            get {
                return ResourceManager.GetString("Info_Detail_Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 編輯 的當地語系化字串。
        /// </summary>
        internal static string Info_Edit {
            get {
                return ResourceManager.GetString("Info_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 首頁 的當地語系化字串。
        /// </summary>
        internal static string Info_Home {
            get {
                return ResourceManager.GetString("Info_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資料新增完成 的當地語系化字串。
        /// </summary>
        internal static string Info_Insert_Success {
            get {
                return ResourceManager.GetString("Info_Insert_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確定刪除？ 的當地語系化字串。
        /// </summary>
        internal static string Info_Is_SureDelete {
            get {
                return ResourceManager.GetString("Info_Is_SureDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 上次登錄 的當地語系化字串。
        /// </summary>
        internal static string Info_Last_Login {
            get {
                return ResourceManager.GetString("Info_Last_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 申請加入中壢青商-{0} 的當地語系化字串。
        /// </summary>
        internal static string Info_Mail_Title_JoinUs {
            get {
                return ResourceManager.GetString("Info_Mail_Title_JoinUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能選單 的當地語系化字串。
        /// </summary>
        internal static string Info_Menu {
            get {
                return ResourceManager.GetString("Info_Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 系統回報訊息 的當地語系化字串。
        /// </summary>
        internal static string Info_Toast_Return_Title {
            get {
                return ResourceManager.GetString("Info_Toast_Return_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資料異動完成 的當地語系化字串。
        /// </summary>
        internal static string Info_Trans_Success {
            get {
                return ResourceManager.GetString("Info_Trans_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資料更新完成 的當地語系化字串。
        /// </summary>
        internal static string Info_Update_Success {
            get {
                return ResourceManager.GetString("Info_Update_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 系統錯誤 的當地語系化字串。
        /// </summary>
        internal static string js_Err_System_Failure {
            get {
                return ResourceManager.GetString("js_Err_System_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 朝敏國際貿易 的當地語系化字串。
        /// </summary>
        internal static string Keywords {
            get {
                return ResourceManager.GetString("Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 最後頁 的當地語系化字串。
        /// </summary>
        internal static string LastPage {
            get {
                return ResourceManager.GetString("LastPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法登錄!狀態不符。 的當地語系化字串。
        /// </summary>
        internal static string Login_Err_Normal {
            get {
                return ResourceManager.GetString("Login_Err_Normal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法登錄!請重輸入帳號或密碼。 的當地語系化字串。
        /// </summary>
        internal static string Login_Err_Password {
            get {
                return ResourceManager.GetString("Login_Err_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 帳號已存在，不可使用。 的當地語系化字串。
        /// </summary>
        internal static string Log_Err_AccountExists {
            get {
                return ResourceManager.GetString("Log_Err_AccountExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 此{0}不存在,請重新選擇!謝謝~! 的當地語系化字串。
        /// </summary>
        internal static string Log_Err_AddCart_Exist {
            get {
                return ResourceManager.GetString("Log_Err_AddCart_Exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 此檔案類型不在充許範圍。 的當地語系化字串。
        /// </summary>
        internal static string Log_Err_AllowFileType {
            get {
                return ResourceManager.GetString("Log_Err_AllowFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 購物車內無此商品~! 的當地語系化字串。
        /// </summary>
        internal static string Log_Err_Cart_ProductExist {
            get {
                return ResourceManager.GetString("Log_Err_Cart_ProductExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 此筆資料已結案!無法刪除!! 的當地語系化字串。
        /// </summary>
        internal static string Log_Err_Delete_Close {
            get {
                return ResourceManager.GetString("Log_Err_Delete_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 此筆資料無法刪除!刪除主檔前需先刪除明細檔或其他參照檔。 的當地語系化字串。
        /// </summary>
        internal static string Log_Err_Delete_DetailExist {
            get {
                return ResourceManager.GetString("Log_Err_Delete_DetailExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 要刪除的資料不存在。 的當地語系化字串。
        /// </summary>
        internal static string Log_Err_Delete_NotFind {
            get {
                return ResourceManager.GetString("Log_Err_Delete_NotFind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 檔案數量超過限制。 的當地語系化字串。
        /// </summary>
        internal static string Log_Err_FileCountOver {
            get {
                return ResourceManager.GetString("Log_Err_FileCountOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 檔案容量超過限制。 的當地語系化字串。
        /// </summary>
        internal static string Log_Err_FileSizeOver {
            get {
                return ResourceManager.GetString("Log_Err_FileSizeOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 此節仍其下仍有資料，需先刪除其下節點才能刪除此節點。 的當地語系化字串。
        /// </summary>
        internal static string Log_Err_HasSubTreeData {
            get {
                return ResourceManager.GetString("Log_Err_HasSubTreeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 輸入的驗證碼不正確，請重新輸入。 的當地語系化字串。
        /// </summary>
        internal static string Log_Err_ImgValideNotEquel {
            get {
                return ResourceManager.GetString("Log_Err_ImgValideNotEquel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 該檔案類型禁止上傳。 的當地語系化字串。
        /// </summary>
        internal static string Log_Err_LimitedFileType {
            get {
                return ResourceManager.GetString("Log_Err_LimitedFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 系統錯誤，無任何資料傳出。 的當地語系化字串。
        /// </summary>
        internal static string Log_Err_MustHaveData {
            get {
                return ResourceManager.GetString("Log_Err_MustHaveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確認密碼和新密碼不一致，請重新輸入。 的當地語系化字串。
        /// </summary>
        internal static string Log_Err_NewPasswordNotSure {
            get {
                return ResourceManager.GetString("Log_Err_NewPasswordNotSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新密碼和舊密碼不可相同。 的當地語系化字串。
        /// </summary>
        internal static string Log_Err_NewPasswordSame {
            get {
                return ResourceManager.GetString("Log_Err_NewPasswordSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 系統無此使用者。 的當地語系化字串。
        /// </summary>
        internal static string Log_Err_NoThisUser {
            get {
                return ResourceManager.GetString("Log_Err_NoThisUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 未選擇客戶 的當地語系化字串。
        /// </summary>
        internal static string Log_Err_Not_Select_Customer {
            get {
                return ResourceManager.GetString("Log_Err_Not_Select_Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 未選擇廠商 的當地語系化字串。
        /// </summary>
        internal static string Log_Err_Not_Select_Supplier {
            get {
                return ResourceManager.GetString("Log_Err_Not_Select_Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 密碼不正確，請重新輸入。 的當地語系化字串。
        /// </summary>
        internal static string Log_Err_Password {
            get {
                return ResourceManager.GetString("Log_Err_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 列印報表需輸入正確查詢條件。 的當地語系化字串。
        /// </summary>
        internal static string Log_Err_PrintCondition {
            get {
                return ResourceManager.GetString("Log_Err_PrintCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 該產品序號已存在。 的當地語系化字串。
        /// </summary>
        internal static string Log_Err_ProdSerialExists {
            get {
                return ResourceManager.GetString("Log_Err_ProdSerialExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 此筆訂單編號不存在，請重新檢查訂單編號! 的當地語系化字串。
        /// </summary>
        internal static string Log_Err_PurchaseExist {
            get {
                return ResourceManager.GetString("Log_Err_PurchaseExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 此筆訂單編號已付款，請重新檢查訂單編號! 的當地語系化字串。
        /// </summary>
        internal static string Log_Err_PurchaseRepeat {
            get {
                return ResourceManager.GetString("Log_Err_PurchaseRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 信箱號碼不正確導致送信失敗，請確認信箱是否正確。 的當地語系化字串。
        /// </summary>
        internal static string Log_Err_SendMailFail {
            get {
                return ResourceManager.GetString("Log_Err_SendMailFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 庫存不足 的當地語系化字串。
        /// </summary>
        internal static string Log_Err_StockNotEnough {
            get {
                return ResourceManager.GetString("Log_Err_StockNotEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 庫存不足[{0}:{1}]，目前庫存數[{2}]。 的當地語系化字串。
        /// </summary>
        internal static string Log_Err_Stock_NotEnough {
            get {
                return ResourceManager.GetString("Log_Err_Stock_NotEnough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Email已送出，我們會儘快與您聯絡! 的當地語系化字串。
        /// </summary>
        internal static string Log_Success_SendMail {
            get {
                return ResourceManager.GetString("Log_Success_SendMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 下一頁 的當地語系化字串。
        /// </summary>
        internal static string NextPage {
            get {
                return ResourceManager.GetString("NextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 上一頁 的當地語系化字串。
        /// </summary>
        internal static string PrevPage {
            get {
                return ResourceManager.GetString("PrevPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 搜尋 的當地語系化字串。
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 朝敏國際貿易 的當地語系化字串。
        /// </summary>
        internal static string System_FrontName {
            get {
                return ResourceManager.GetString("System_FrontName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 朝敏國際貿易 管理系統 的當地語系化字串。
        /// </summary>
        internal static string System_Name {
            get {
                return ResourceManager.GetString("System_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Chaomin International Trading 的當地語系化字串。
        /// </summary>
        internal static string System_Name_En {
            get {
                return ResourceManager.GetString("System_Name_En", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無項目 的當地語系化字串。
        /// </summary>
        internal static string ViewbagCapton {
            get {
                return ResourceManager.GetString("ViewbagCapton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能選單 的當地語系化字串。
        /// </summary>
        internal static string ViewbagMenuName {
            get {
                return ResourceManager.GetString("ViewbagMenuName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇要刪除的列。 的當地語系化字串。
        /// </summary>
        internal static string Warn_Select_Delete_Data {
            get {
                return ResourceManager.GetString("Warn_Select_Delete_Data", resourceCulture);
            }
        }
    }
}
